import {
  Student,
  Teacher,
  Batch,
  BatchAttendance,
  FeeInstallment,
  ExamTest,
  StudentExamMark,
  Homework,
  StudyMaterial,
  TimetableSlot,
  WhatsAppMessage,
} from './types';

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'batch-1',
    name: 'JEE Adv Titans (12th)',
    courseName: 'JEE Advanced + Mains Integrated',
    grade: 'Class 12',
    subject: 'Physics, Chem, Maths',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Rajesh Verma',
    scheduleDays: ['Mon', 'Wed', 'Fri'],
    startTime: '04:00 PM',
    endTime: '06:30 PM',
    room: 'Hall A (Smart Lab)',
    capacity: 35,
    enrolledCount: 28,
    annualFee: 85000,
    accentColor: '#4f46e5',
    academicYear: '2026-2027',
  },
  {
    id: 'batch-2',
    name: 'NEET Super-30 (12th)',
    courseName: 'Medical Entrance Masterclass',
    grade: 'Class 12',
    subject: 'Physics, Chem, Biology',
    teacherId: 'teacher-2',
    teacherName: 'Prof. Ananya Sen',
    scheduleDays: ['Tue', 'Thu', 'Sat'],
    startTime: '04:00 PM',
    endTime: '06:30 PM',
    room: 'Hall B',
    capacity: 30,
    enrolledCount: 24,
    annualFee: 90000,
    accentColor: '#059669',
    academicYear: '2026-2027',
  },
  {
    id: 'batch-3',
    name: 'Class 10 CBSE Achievers',
    courseName: 'Board Exam Centum Batch',
    grade: 'Class 10',
    subject: 'Maths & Science',
    teacherId: 'teacher-3',
    teacherName: 'Er. Vikas Sharma',
    scheduleDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    startTime: '06:30 PM',
    endTime: '08:00 PM',
    room: 'Room 102',
    capacity: 40,
    enrolledCount: 36,
    annualFee: 45000,
    accentColor: '#d97706',
    academicYear: '2026-2027',
  },
  {
    id: 'batch-4',
    name: 'Class 9 Foundation Olympiad',
    courseName: 'NTSE & Olympiad Prep',
    grade: 'Class 9',
    subject: 'Science & Aptitude',
    teacherId: 'teacher-1',
    teacherName: 'Dr. Rajesh Verma',
    scheduleDays: ['Tue', 'Thu', 'Sat'],
    startTime: '06:30 PM',
    endTime: '08:00 PM',
    room: 'Room 104',
    capacity: 25,
    enrolledCount: 18,
    annualFee: 40000,
    accentColor: '#0284c7',
    academicYear: '2026-2027',
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'teacher-1',
    name: 'Dr. Rajesh Verma',
    email: 'rajesh.verma@apexacademy.edu',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    subjects: ['Physics (Mechanics & Electrodynamics)', 'Olympiad Science'],
    qualifications: 'Ph.D. IIT Delhi, Ex-FIITJEE Faculty (14 yrs exp)',
    joiningDate: '2021-04-01',
    status: 'active',
    assignedBatches: ['batch-1', 'batch-4'],
  },
  {
    id: 'teacher-2',
    name: 'Prof. Ananya Sen',
    email: 'ananya.sen@apexacademy.edu',
    phone: '+91 98111 22334',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    subjects: ['Biology (Genetics & Zoology)', 'Chemistry (Organic)'],
    qualifications: 'M.Sc. AIIMS Fellow, Gold Medalist (9 yrs exp)',
    joiningDate: '2022-06-15',
    status: 'active',
    assignedBatches: ['batch-2'],
  },
  {
    id: 'teacher-3',
    name: 'Er. Vikas Sharma',
    email: 'vikas.sharma@apexacademy.edu',
    phone: '+91 99223 34455',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    subjects: ['Mathematics (Calculus & Coordinate)', 'CBSE Board Prep'],
    qualifications: 'B.Tech NIT Kurukshetra, Ex-Allen Senior Faculty (8 yrs exp)',
    joiningDate: '2023-01-10',
    status: 'active',
    assignedBatches: ['batch-3'],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'student-1',
    rollNo: 'APX-2026-001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    phone: '+91 98201 11223',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    gender: 'Male',
    dob: '2008-05-14',
    address: 'B-402, Sunrise Towers, Model Town, Delhi',
    schoolName: 'Delhi Public School, R.K. Puram',
    parentName: 'Sunil Sharma',
    parentPhone: '+91 98201 99887',
    parentEmail: 'sunil.sharma@business.com',
    parentRelation: 'Father',
    batchIds: ['batch-1'],
    enrollmentDate: '2026-04-10',
    status: 'active',
    totalFee: 85000,
    paidFee: 55000,
    pendingFee: 30000,
  },
  {
    id: 'student-2',
    rollNo: 'APX-2026-002',
    name: 'Diya Patel',
    email: 'diya.patel@gmail.com',
    phone: '+91 98333 44556',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    gender: 'Female',
    dob: '2008-09-22',
    address: 'Flat 12, Gulmohar Enclave, Noida',
    schoolName: 'Lotus Valley International',
    parentName: 'Ramesh Patel',
    parentPhone: '+91 98333 88990',
    parentEmail: 'ramesh.patel@corporate.in',
    parentRelation: 'Father',
    batchIds: ['batch-2'],
    enrollmentDate: '2026-04-12',
    status: 'active',
    totalFee: 90000,
    paidFee: 90000,
    pendingFee: 0,
  },
  {
    id: 'student-3',
    rollNo: 'APX-2026-003',
    name: 'Rohan Deshmukh',
    email: 'rohan.deshmukh@gmail.com',
    phone: '+91 97654 32109',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    gender: 'Male',
    dob: '2010-02-18',
    address: 'C-101, Green Meadows, Gurgaon',
    schoolName: 'The Heritage School',
    parentName: 'Meera Deshmukh',
    parentPhone: '+91 97654 11223',
    parentEmail: 'meera.deshmukh@gmail.com',
    parentRelation: 'Mother',
    batchIds: ['batch-3'],
    enrollmentDate: '2026-04-15',
    status: 'active',
    totalFee: 45000,
    paidFee: 25000,
    pendingFee: 20000,
  },
  {
    id: 'student-4',
    rollNo: 'APX-2026-004',
    name: 'Ananya Gupta',
    email: 'ananya.gupta@gmail.com',
    phone: '+91 98450 67890',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    gender: 'Female',
    dob: '2008-11-03',
    address: '14/3 Rajendra Nagar, New Delhi',
    schoolName: 'Bal Bharati Public School',
    parentName: 'Pradeep Gupta',
    parentPhone: '+91 98450 12345',
    parentEmail: 'pradeep.gupta@consultant.com',
    parentRelation: 'Father',
    batchIds: ['batch-1'],
    enrollmentDate: '2026-04-18',
    status: 'active',
    totalFee: 85000,
    paidFee: 85000,
    pendingFee: 0,
  },
  {
    id: 'student-5',
    rollNo: 'APX-2026-005',
    name: 'Kabir Singhania',
    email: 'kabir.singhania@gmail.com',
    phone: '+91 98190 55443',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    gender: 'Male',
    dob: '2011-08-30',
    address: 'Villa 7, Palm Greens, Greater Noida',
    schoolName: 'Step by Step School',
    parentName: 'Vikram Singhania',
    parentPhone: '+91 98190 99887',
    parentEmail: 'vikram.singhania@finance.org',
    parentRelation: 'Father',
    batchIds: ['batch-4'],
    enrollmentDate: '2026-04-20',
    status: 'active',
    totalFee: 40000,
    paidFee: 20000,
    pendingFee: 20000,
  },
  {
    id: 'student-6',
    rollNo: 'APX-2026-006',
    name: 'Isha Reddy',
    email: 'isha.reddy@gmail.com',
    phone: '+91 98770 12345',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    gender: 'Female',
    dob: '2008-07-19',
    address: 'H-302, Cyber Heights, Sector 62, Noida',
    schoolName: 'Amity International School',
    parentName: 'Suresh Reddy',
    parentPhone: '+91 98770 99881',
    parentEmail: 'suresh.reddy@tech.com',
    parentRelation: 'Father',
    batchIds: ['batch-2'],
    enrollmentDate: '2026-04-25',
    status: 'active',
    totalFee: 90000,
    paidFee: 45000,
    pendingFee: 45000,
  },
];

export const INITIAL_INSTALLMENTS: FeeInstallment[] = [
  {
    id: 'inst-1',
    studentId: 'student-1',
    installmentNo: 1,
    title: 'Term 1 Admission & Tuition Fee',
    dueDate: '2026-04-15',
    amount: 30000,
    status: 'paid',
    paidDate: '2026-04-12',
    paymentMode: 'UPI',
    transactionId: 'UPI/260412/98421045',
    receiptNumber: 'REC-2026-0412',
  },
  {
    id: 'inst-2',
    studentId: 'student-1',
    installmentNo: 2,
    title: 'Term 2 Tuition & Test Series Fee',
    dueDate: '2026-07-15',
    amount: 25000,
    status: 'paid',
    paidDate: '2026-07-14',
    paymentMode: 'Razorpay',
    transactionId: 'pay_Nkd81xLkjA9',
    receiptNumber: 'REC-2026-0714',
  },
  {
    id: 'inst-3',
    studentId: 'student-1',
    installmentNo: 3,
    title: 'Term 3 Final Revision & Mock Exams',
    dueDate: '2026-10-15',
    amount: 30000,
    status: 'pending',
    paymentLink: 'https://pages.razorpay.com/pl_apex_aarav_term3',
  },
  {
    id: 'inst-4',
    studentId: 'student-2',
    installmentNo: 1,
    title: 'Full Course Lumsum (10% Waiver)',
    dueDate: '2026-04-15',
    amount: 90000,
    status: 'paid',
    paidDate: '2026-04-12',
    paymentMode: 'Bank Transfer',
    transactionId: 'NEFT/HDFC/20260412001',
    receiptNumber: 'REC-2026-0413',
  },
  {
    id: 'inst-5',
    studentId: 'student-3',
    installmentNo: 1,
    title: 'Term 1 Board Foundation Fee',
    dueDate: '2026-04-20',
    amount: 25000,
    status: 'paid',
    paidDate: '2026-04-18',
    paymentMode: 'Cash',
    transactionId: 'CASH-REC-1029',
    receiptNumber: 'REC-2026-0418',
  },
  {
    id: 'inst-6',
    studentId: 'student-3',
    installmentNo: 2,
    title: 'Term 2 Board Revision Fee',
    dueDate: '2026-08-30',
    amount: 20000,
    status: 'overdue',
    paymentLink: 'https://pages.razorpay.com/pl_apex_rohan_term2',
  },
  {
    id: 'inst-7',
    studentId: 'student-6',
    installmentNo: 1,
    title: 'Installment 1 - NEET Super 30',
    dueDate: '2026-04-30',
    amount: 45000,
    status: 'paid',
    paidDate: '2026-04-28',
    paymentMode: 'UPI',
    transactionId: 'UPI/260428/776655',
    receiptNumber: 'REC-2026-0428',
  },
  {
    id: 'inst-8',
    studentId: 'student-6',
    installmentNo: 2,
    title: 'Installment 2 - NEET Super 30',
    dueDate: '2026-09-10',
    amount: 45000,
    status: 'pending',
    paymentLink: 'https://pages.razorpay.com/pl_apex_isha_term2',
  },
];

export const INITIAL_ATTENDANCE: BatchAttendance[] = [
  {
    id: 'att-1',
    batchId: 'batch-1',
    batchName: 'JEE Adv Titans (12th)',
    date: '2026-09-04',
    markedBy: 'Dr. Rajesh Verma',
    markedAt: '04:15 PM',
    whatsappDispatched: true,
    absentCount: 1,
    presentCount: 27,
    records: [
      { studentId: 'student-1', status: 'present' },
      { studentId: 'student-4', status: 'present' },
    ],
  },
  {
    id: 'att-2',
    batchId: 'batch-2',
    batchName: 'NEET Super-30 (12th)',
    date: '2026-09-04',
    markedBy: 'Prof. Ananya Sen',
    markedAt: '04:10 PM',
    whatsappDispatched: true,
    absentCount: 1,
    presentCount: 23,
    records: [
      { studentId: 'student-2', status: 'present' },
      { studentId: 'student-6', status: 'absent', remarks: 'Fever reported by parent' },
    ],
  },
  {
    id: 'att-3',
    batchId: 'batch-3',
    batchName: 'Class 10 CBSE Achievers',
    date: '2026-09-03',
    markedBy: 'Er. Vikas Sharma',
    markedAt: '06:35 PM',
    whatsappDispatched: true,
    absentCount: 2,
    presentCount: 34,
    records: [
      { studentId: 'student-3', status: 'present' },
    ],
  },
];

export const INITIAL_EXAMS: ExamTest[] = [
  {
    id: 'exam-1',
    title: 'JEE Minor Test 04 — Electrostatics & Calculus',
    batchId: 'batch-1',
    batchName: 'JEE Adv Titans (12th)',
    subject: 'Physics & Maths',
    examDate: '2026-08-28',
    totalMarks: 180,
    passingMarks: 72,
    status: 'evaluated',
    averageScore: 124,
    highestScore: 172,
  },
  {
    id: 'exam-2',
    title: 'NEET Grand Mock 03 — Human Physiology & Organic Chem',
    batchId: 'batch-2',
    batchName: 'NEET Super-30 (12th)',
    subject: 'Biology & Chemistry',
    examDate: '2026-08-30',
    totalMarks: 360,
    passingMarks: 180,
    status: 'evaluated',
    averageScore: 288,
    highestScore: 348,
  },
  {
    id: 'exam-3',
    title: 'Class 10 Half-Yearly Science & Maths Prep Test',
    batchId: 'batch-3',
    batchName: 'Class 10 CBSE Achievers',
    subject: 'Science & Maths',
    examDate: '2026-09-12',
    totalMarks: 100,
    passingMarks: 40,
    status: 'scheduled',
  },
];

export const INITIAL_MARKS: StudentExamMark[] = [
  {
    id: 'mark-1',
    examId: 'exam-1',
    studentId: 'student-1',
    studentName: 'Aarav Sharma',
    rollNo: 'APX-2026-001',
    marksObtained: 158,
    totalMarks: 180,
    percentage: 87.8,
    rank: 2,
    grade: 'A+',
    teacherRemarks: 'Exceptional in Electrodynamics. Work on Speed in Integral Calculus.',
    whatsappSent: true,
  },
  {
    id: 'mark-2',
    examId: 'exam-1',
    studentId: 'student-4',
    studentName: 'Ananya Gupta',
    rollNo: 'APX-2026-004',
    marksObtained: 172,
    totalMarks: 180,
    percentage: 95.5,
    rank: 1,
    grade: 'A+',
    teacherRemarks: 'Batch topper! Flawless conceptual clarity.',
    whatsappSent: true,
  },
  {
    id: 'mark-3',
    examId: 'exam-2',
    studentId: 'student-2',
    studentName: 'Diya Patel',
    rollNo: 'APX-2026-002',
    marksObtained: 342,
    totalMarks: 360,
    percentage: 95.0,
    rank: 1,
    grade: 'A+',
    teacherRemarks: 'Top-tier performance in Human Physiology. Consistent ranker.',
    whatsappSent: true,
  },
  {
    id: 'mark-4',
    examId: 'exam-2',
    studentId: 'student-6',
    studentName: 'Isha Reddy',
    rollNo: 'APX-2026-006',
    marksObtained: 278,
    totalMarks: 360,
    percentage: 77.2,
    rank: 8,
    grade: 'B+',
    teacherRemarks: 'Good attempt. Needs revision in Reaction Mechanisms.',
    whatsappSent: true,
  },
];

export const INITIAL_HOMEWORK: Homework[] = [
  {
    id: 'hw-1',
    title: 'Physics DPP #14: Rotational Dynamics & Center of Mass',
    batchId: 'batch-1',
    batchName: 'JEE Adv Titans (12th)',
    subject: 'Physics',
    teacherName: 'Dr. Rajesh Verma',
    assignedDate: '2026-09-02',
    dueDate: '2026-09-06',
    description: 'Solve problems 1 to 25 from Advanced Sheet. Show full free-body diagrams.',
    submissionCount: 22,
    totalStudents: 28,
    attachments: [{ name: 'DPP_14_Rotational_Motion.pdf', size: '1.8 MB' }],
  },
  {
    id: 'hw-2',
    title: 'Zoology Worksheet: Neural Control & Reflex Arcs',
    batchId: 'batch-2',
    batchName: 'NEET Super-30 (12th)',
    subject: 'Biology',
    teacherName: 'Prof. Ananya Sen',
    assignedDate: '2026-09-03',
    dueDate: '2026-09-07',
    description: 'Complete NCERT exemplar diagrams and label synaptic transmission flow.',
    submissionCount: 20,
    totalStudents: 24,
    attachments: [{ name: 'Neural_Control_Exemplar.pdf', size: '2.4 MB' }],
  },
  {
    id: 'hw-3',
    title: 'Maths Assignment: Quadratic Equations & AP Word Problems',
    batchId: 'batch-3',
    batchName: 'Class 10 CBSE Achievers',
    subject: 'Mathematics',
    teacherName: 'Er. Vikas Sharma',
    assignedDate: '2026-09-04',
    dueDate: '2026-09-08',
    description: 'Previous 5 years CBSE board question bank (Questions 1 to 30).',
    submissionCount: 15,
    totalStudents: 36,
    attachments: [{ name: 'Class10_Maths_PYQ_Chapter4_5.pdf', size: '3.1 MB' }],
  },
];

export const INITIAL_STUDY_MATERIALS: StudyMaterial[] = [
  {
    id: 'mat-1',
    title: 'Comprehensive Physics Formula Handbook (Mechanics & Electromagnetism)',
    batchId: 'batch-1',
    batchName: 'JEE Adv Titans (12th)',
    subject: 'Physics',
    type: 'pdf',
    fileName: 'JEE_Physics_Formula_Book_v2.pdf',
    fileSize: '4.2 MB',
    uploadedAt: '2026-08-20',
  },
  {
    id: 'mat-2',
    title: 'High-Yield NEET Biology Mindmaps & Diagram Flashcards',
    batchId: 'batch-2',
    batchName: 'NEET Super-30 (12th)',
    subject: 'Biology',
    type: 'pdf',
    fileName: 'NEET_Bio_Mindmaps_Color.pdf',
    fileSize: '8.7 MB',
    uploadedAt: '2026-08-22',
  },
  {
    id: 'mat-3',
    title: 'Class 10 CBSE Centum Revision Notes: Physics & Chem Formula Sheet',
    batchId: 'batch-3',
    batchName: 'Class 10 CBSE Achievers',
    subject: 'Science',
    type: 'pdf',
    fileName: 'Class10_Centum_Revision_Notes.pdf',
    fileSize: '3.5 MB',
    uploadedAt: '2026-08-25',
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  {
    id: 'tt-1',
    day: 'Monday',
    time: '04:00 PM - 06:30 PM',
    batchName: 'JEE Adv Titans (12th)',
    subject: 'Physics & Advanced Mechanics',
    teacherName: 'Dr. Rajesh Verma',
    room: 'Hall A (Smart Lab)',
    color: '#4f46e5',
  },
  {
    id: 'tt-2',
    day: 'Monday',
    time: '06:30 PM - 08:00 PM',
    batchName: 'Class 10 CBSE Achievers',
    subject: 'Maths (Coordinate Geometry)',
    teacherName: 'Er. Vikas Sharma',
    room: 'Room 102',
    color: '#d97706',
  },
  {
    id: 'tt-3',
    day: 'Tuesday',
    time: '04:00 PM - 06:30 PM',
    batchName: 'NEET Super-30 (12th)',
    subject: 'Zoology & Genetic Mechanisms',
    teacherName: 'Prof. Ananya Sen',
    room: 'Hall B',
    color: '#059669',
  },
  {
    id: 'tt-4',
    day: 'Tuesday',
    time: '06:30 PM - 08:00 PM',
    batchName: 'Class 9 Foundation Olympiad',
    subject: 'Science Aptitude & Physics',
    teacherName: 'Dr. Rajesh Verma',
    room: 'Room 104',
    color: '#0284c7',
  },
  {
    id: 'tt-5',
    day: 'Wednesday',
    time: '04:00 PM - 06:30 PM',
    batchName: 'JEE Adv Titans (12th)',
    subject: 'Calculus & Integral Applications',
    teacherName: 'Er. Vikas Sharma',
    room: 'Hall A (Smart Lab)',
    color: '#4f46e5',
  },
];

export const INITIAL_WHATSAPP_LOGS: WhatsAppMessage[] = [
  {
    id: 'wa-1',
    recipientName: 'Suresh Reddy (Parent of Isha)',
    recipientPhone: '+91 98770 99881',
    recipientRole: 'parent',
    type: 'absence_alert',
    content: '🚨 *Apex Academy Attendance Alert*\n\nDear Suresh Reddy,\nThis is to inform you that *Isha Reddy* was marked *ABSENT* for *NEET Super-30 (12th)* today (04-Sep-2026).\n\nIf this was unplanned, please contact academy front-desk at +91 98765 00000.',
    status: 'read',
    timestamp: 'Today, 04:12 PM',
    meta: { studentName: 'Isha Reddy', batchName: 'NEET Super-30' },
  },
  {
    id: 'wa-2',
    recipientName: 'Meera Deshmukh (Parent of Rohan)',
    recipientPhone: '+91 97654 11223',
    recipientRole: 'parent',
    type: 'fee_reminder',
    content: '💳 *Apex Academy Fee Reminder*\n\nDear Meera Deshmukh,\nFee installment of *₹20,000* for *Rohan Deshmukh* is overdue (Due: 30-Aug-2026).\n\nPay securely via 1-Click UPI:\n👉 https://pages.razorpay.com/pl_apex_rohan_term2\n\nInstant digital receipt will be generated automatically.',
    status: 'delivered',
    timestamp: 'Today, 10:30 AM',
    meta: { studentName: 'Rohan Deshmukh', amount: 20000, paymentLink: 'https://pages.razorpay.com/pl_apex_rohan_term2' },
  },
  {
    id: 'wa-3',
    recipientName: 'Sunil Sharma (Parent of Aarav)',
    recipientPhone: '+91 98201 99887',
    recipientRole: 'parent',
    type: 'report_card',
    content: '📊 *Apex Academy — Test Report Published*\n\nDear Sunil Sharma,\n*Aarav Sharma* scored *158 / 180 (87.8%)* with *Rank #2* in *JEE Minor Test 04*.\n\n📄 PDF Report Card with detailed question breakdown and rank graph has been generated.\n\nView Portal: https://apexacademy.app/parent',
    status: 'read',
    timestamp: 'Yesterday, 06:45 PM',
    meta: { studentName: 'Aarav Sharma', pdfType: 'Report Card' },
  },
  {
    id: 'wa-4',
    recipientName: 'Ramesh Patel (Parent of Diya)',
    recipientPhone: '+91 98333 88990',
    recipientRole: 'parent',
    type: 'payment_receipt',
    content: '✅ *Payment Received — Apex Academy*\n\nDear Ramesh Patel,\nWe successfully received *₹90,000* for *Diya Patel* (Receipt #REC-2026-0413).\n\nThank you for choosing Apex Academy!',
    status: 'read',
    timestamp: '12-Apr-2026, 02:15 PM',
    meta: { studentName: 'Diya Patel', amount: 90000 },
  },
];
